[build]
builder = "NIXPACKS"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
source = "openrouter-chat-backend"
rootDirectory = "/openrouter-chat-backend"

[services.healthcheck]
path = "/api/health"
port = 3001

[[services]]
source = "openrouter-chat-frontend"
rootDirectory = "/openrouter-chat-frontend"

[services.healthcheck]
path = "/"
port = 3000
